# import streamlit as st

# def render_math_explanation():
#     st.markdown("## 📚 Mathematical Formulation & Methodology")
    
#     # --- 1. Stochastic Control Framework ---
#     st.markdown("### 1. The Stochastic Control Framework")
#     st.markdown(r"""
#     We model the credit lifecycle as a **Discrete-Time Inhomogeneous Markov Chain** adapted to a Competing Risks framework. 
#     Let $(\Omega, \mathcal{F}, \mathbb{P})$ be a filtered probability space. The state of the loan $X_t$ at time $t$ evolves on the finite state space $\mathcal{S}$:
    
#     $$
#     \mathcal{S} = \{ \underbrace{0: \text{Current}, 1: \text{Late}}_{\text{Transient}}, \underbrace{2: \text{Default}, 3: \text{Prepaid}}_{\text{Absorbing}} \}
#     $$

#     The system dynamics are governed by the **Transition Probability Matrix** $\mathbf{P}_t$, conditional on the filtration $\mathcal{F}_t$ (the information set generated by covariates $\mathbf{z}_t$ such as FICO, Rate Spread, and Loan Age):

#     $$
#     p_{ij}(t, \mathbf{z}_t) = \mathbb{P}(X_{t+1} = j \mid X_t = i, \mathcal{F}_t)
#     $$

#     Unlike homogeneous chains, the kernel $p_{ij}(\cdot)$ is **stochastic** and controlled by the exogenous process $\mathbf{z}_t$.
#     """)

#     st.divider()

#     # --- 2. The Estimator ---
#     st.markdown("### 2. Non-Parametric Estimation (XGBoost)")
#     st.markdown(r"""
#     To estimate the transition kernel $p_{ij}(t, \mathbf{z}_t)$, we employ **Extreme Gradient Boosting (XGBoost)** as a function approximator. 
#     We approximate the log-intensity functions $F_j(\mathbf{z})$ using an additive expansion of $K$ regression trees:
    
#     $$
#     F_j(\mathbf{z}_t) = \sum_{k=1}^K f_k(\mathbf{z}_t), \quad f_k \in \mathcal{H}
#     $$
    
#     To ensure the output satisfies the Kolmogorov axioms ($\sum p = 1$), we apply the **Softmax Transformation** (Multinomial Logistic Link):

#     $$
#     \hat{p}_{ij}(\mathbf{z}_t) = \frac{\exp\left(F_j(\mathbf{z}_t)\right)}{\sum_{k \in \mathcal{S}} \exp\left(F_k(\mathbf{z}_t)\right)}
#     $$

#     **Optimization Objective:**
#     The model minimizes the **Regularized Multi-Class Log-Loss** (Cross-Entropy). XGBoost performs this via a Second-Order Taylor Expansion (Newton-Raphson method) of the loss $\mathcal{L}$:

#     $$
#     \mathcal{L}^{(t)} \approx \sum_{i=1}^N \left[ g_i f_t(\mathbf{z}_i) + \frac{1}{2} h_i f_t^2(\mathbf{z}_i) \right] + \Omega(f_t)
#     $$

#     Where $g_i, h_i$ are the gradient and Hessian, and $\Omega$ is the regularization term penalizing tree complexity.
#     """)

#     st.divider()

#     # --- 3. Flux Valuation ---
#     st.markdown("### 3. Flux Expectation (Stopping Times)")
#     st.markdown(r"""
#     The **Expected Flux** $\mathbb{E}[CF_t]$ is computed via Vectorized Monte Carlo simulation. 
#     Let $\tau = \inf \{ t > 0 : X_t \in \{2, 3\} \}$ be the stopping time for absorbing states. The cash flow process $C_t$ is defined as:

#     $$
#     C_t = 
#     \begin{cases} 
#     \text{PMT} & \text{if } X_t = 0 \\
#     B_t \cdot (1 - \text{LGD}) & \text{if } X_t = 2 \quad (\text{Default}) \\
#     B_t & \text{if } X_t = 3 \quad (\text{Prepayment}) \\
#     0 & \text{otherwise}
#     \end{cases}
#     $$

#     We estimate the expectation and Value-at-Risk (VaR) using $N=2000$ paths:
#     $$
#     \hat{\mathbb{E}}[C_t] \approx \frac{1}{N} \sum_{n=1}^N C_t^{(n)}
#     $$
#     """)

#     st.divider()

#     # --- 4. References ---
#     st.markdown("### 📚 Academic References")
#     st.markdown("""
#     1.  **Deng, Y., Quigley, J. M., & Van Order, R. (2000).** *Mortgage Terminations, Heterogeneity and the Exercise of Mortgage Options.* Econometrica.
#         *   *Significance:* The seminal paper on Competing Risks (Default vs Prepayment).
#     2.  **Duffie, D., Saita, L., & Wang, K. (2007).** *Multi-period corporate default prediction with stochastic covariates.* Journal of Financial Economics.
#         *   *Significance:* Establishes the discrete-time hazard model framework.
#     3.  **Friedman, J. H. (2001).** *Greedy function approximation: A gradient boosting machine.* Annals of Statistics.
#         *   *Significance:* Proves that Boosting is a gradient descent optimization in function space.
#     4.  **Lando, D. (2004).** *Credit Risk Modeling: Theory and Applications.* Princeton University Press.
#     """)

import streamlit as st

def render_math_explanation():
    st.markdown("## 📚 Mathematical Formulation: Stochastic Impulse Control")
    
    st.info("""
    **Model Evolution:** We have transitioned from a Discrete-Time Markov Chain (DTMC) to a **Hybrid Impulse Control Model**. 
    Instead of discrete states, we model the **Payment Fraction Measure** directly to capture partial prepayments.
    """)

    # --- 1. The Measure Space ---
    st.markdown("### 1. The Singular Payment Measure")
    st.markdown(r"""
    Let $Y_t \in [0, 1]$ be the random variable representing the **fraction of the outstanding balance paid** at time $t$. 
    The probability distribution of $Y_t$ is **Singular** (neither purely continuous nor purely discrete). It is a **Mixed Measure** defined as:

    $$
    \mathbb{P}(Y_t \in dy \mid \mathcal{F}_{t-1}) = \underbrace{\pi_d(\mathbf{z}_t) \cdot \delta_0(dy)}_{\text{Default (Atom at 0)}} + \underbrace{\pi_p(\mathbf{z}_t) \cdot \delta_1(dy)}_{\text{Prepayment (Atom at 1)}} + \underbrace{\pi_c(\mathbf{z}_t) \cdot f(y; \theta) dy}_{\text{Continuing (Density)}}
    $$

    Where:
    *   $\delta_x(\cdot)$ is the Dirac Delta measure (Mass Point).
    *   $\pi_d, \pi_p, \pi_c$ are the regime probabilities ($\sum \pi = 1$), driven by the **Topological Router**.
    *   $f(y)$ is the density of partial payments for continuing loans, driven by the **Flux Expert**.
    """)

    st.divider()

    # --- 2. System Dynamics ---
    st.markdown("### 2. State Dynamics (The Impulse)")
    st.markdown(r"""
    The outstanding balance process $B_t$ evolves according to a stochastic difference equation controlled by the impulse $Y_t$:

    $$
    B_{t+1} = \underbrace{B_t \cdot (1 + r \Delta t)}_{\text{Interest Accrual}} - \underbrace{B_t \cdot Y_t}_{\text{Stochastic Impulse}}
    $$

    This formulation captures the **Path Dependency** of the credit risk:
    1.  If $Y_t = 1$ (Prepay), $B_{t+1} \to 0$ instantly (Absorption).
    2.  If $Y_t = 0$ (Default), $B_{t+1} \to 0$ (Absorption into Recovery).
    3.  If $0 < Y_t < 1$, the loan remains transient but the exposure decreases (Curtailment).
    """)

    st.divider()

    # --- 3. Estimation Strategy (ZOIB) ---
    st.markdown("### 3. Estimation: Zero-One Inflated Framework")
    st.markdown(r"""
    To estimate the parameters of this mixed measure, we employ a **Two-Stage Estimator**:

    **Stage A: Topological Classification (The Router)**
    We estimate the regime $\hat{k} \in \{ \text{Def, Cont, Pre} \}$ using Gradient Boosting with the Softmax objective:
    $$ \hat{\pi}_k(\mathbf{x}) = \frac{e^{F_k(\mathbf{x})}}{\sum_j e^{F_j(\mathbf{x})}} $$

    **Stage B: Conditional Flux Control (The Expert)**
    Conditional on $k = \text{Cont}$, we estimate the payment fraction $y$. Since $y \in (0,1)$, we use a **Logit-Link Regressor** to strictly bound the predictions:
    $$ \hat{y} = \sigma\left( G(\mathbf{x}) \right) = \frac{1}{1 + e^{-G(\mathbf{x})}} $$
    
    This ensures mathematical consistency: the model cannot predict negative payments or payments exceeding the balance.
    """)
